CREATE TABLE IF NOT EXISTS public.permission (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description character varying(255)
);

ALTER TABLE public.permission OWNER TO postgres;

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);