CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name character varying(255),
    full_name character varying(255),
    password character varying(255),
    account_non_expired bit,
    account_non_locked bit,
    credentials_non_expired bit,
    enabled bit
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);